# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3393cc58c8b4412611013d98324b9bc69c5a7a9a03446e0a21b2fd01c8d1b32b67637bd585bad286704fd881e578f1c2366b5911902463bb6622455150ee46

test:
  secret_key_base: d345548ebdabdbf13052c699ac0796e6be1656cb35cf9e4e448ec90393e8ee82a305302bb833e0147f67b08593daa9947b9413223fd35bbbadd780dcb4d80898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
